#pragma once
const int HEROS_HOBBITS = 20, VILLAINS_HOBBITS = 10, HEROS_ELFS = 5,VILLAINS_ELFS = 3, HEROS_DWARFS = 5, VILLAINS_DWARFS = 10;
const int HEROS_MAGICIANS = 2, VILLAINS_MAGICIANS = 3, HEROS_NAZGULS = 1,VILLAINS_NAZGULS = 1;
const int FIELD = 100;

const int HOBBIT_LIVES = 3, ELF_LIVES = 10, DWARF_LIVES = 5, MAGICIAN_LIVES = 20, NAZGUL_LIVES = 50;
const int NUMBER_OF_ARROWS = 10, NUMBER_OF_AXES = 10, NUMBER_OF_BONUS_JUST_TO_KILL = 3;
const char FRODO = 'F', SAYRON = 'S';
